apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: app
data:
  application.properties: |
  # Example properties â€” adjust for your app
    server.port=8080
    management.endpoints.web.exposure.include=health,info,prometheus
    management.endpoint.health.show-details=always
    management.metrics.export.simple.enabled=true
    management.endpoints.web.base-path=/actuator